import { HOST_PROFLE } from "./image";

export  const profiles = [
    {
      id: 1,
      name: "Bonita",
      age: 25,
      location: "Manila City",
      birthday: "February 01",
      zodiac: "Aquarius",
      hobby: "Dancing",
      likes: "2.3k",
      image: HOST_PROFLE.bonita.src,
      badge: "1"
    },
    {
      id: 2,
      name: "Ace",
      age: 24,
      location: "Quezon City",
      birthday: "March 15",
      zodiac: "Pisces",
      hobby: "Gaming",
      likes: "1.8k",
      image: HOST_PROFLE.ace.src,
      badge: "2"
    },
    {
      id: 3,
      name: "Alex",
      age: 26,
      location: "Makati City",
      birthday: "July 22",
      zodiac: "Cancer",
      hobby: "Music",
      likes: "3.1k",
      image: HOST_PROFLE.alex.src,
      badge: "3"
    },
    {
      id: 4,
      name: "Charm",
      age: 23,
      location: "Pasig City",
      birthday: "November 08",
      zodiac: "Scorpio",
      hobby: "Fashion",
      likes: "2.7k",
      image: HOST_PROFLE.charm.src,
      badge: "4"
    },
    {
      id: 5,
      name: "Devon",
      age: 27,
      location: "Taguig City",
      birthday: "September 12",
      zodiac: "Virgo",
      hobby: "Sports",
      likes: "4.2k",
      image: HOST_PROFLE.devon.src,
      badge: "5"
    },
    {
      id: 6,
      name: "Ellise",
      age: 25,
      location: "Mandaluyong",
      birthday: "April 18",
      zodiac: "Aries",
      hobby: "Art",
      likes: "3.5k",
      image: HOST_PROFLE.ellise.src,
      badge: "6"
    },
    {
      id: 7,
      name: "Eve",
      age: 22,
      location: "Pasay City",
      birthday: "June 30",
      zodiac: "Cancer",
      hobby: "Yoga",
      likes: "2.9k",
      image: HOST_PROFLE.eve.src,
      badge: "7"
    },
    {
      id: 8,
      name: "Evo",
      age: 28,
      location: "BGC",
      birthday: "October 14",
      zodiac: "Libra",
      hobby: "Fitness",
      likes: "5.1k",
      image: HOST_PROFLE.evo.src,
      badge: "8"
    },
    {
      id: 9,
      name: "Geoff",
      age: 26,
      location: "Ortigas",
      birthday: "January 25",
      zodiac: "Aquarius",
      hobby: "Photography",
      likes: "3.8k",
      image: HOST_PROFLE.geoff.src,
      badge: "9"
    },
    {
      id: 10,
      name: "Jlai",
      age: 24,
      location: "Alabang",
      birthday: "May 05",
      zodiac: "Taurus",
      hobby: "Cooking",
      likes: "2.4k",
      image: HOST_PROFLE.jlai.src,
      badge: "10"
    },
    {
      id: 11,
      name: "Kylie",
      age: 23,
      location: "San Juan",
      birthday: "August 17",
      zodiac: "Leo",
      hobby: "Singing",
      likes: "4.6k",
      image: HOST_PROFLE.kylie.src,
      badge: "11"
    },
    {
      id: 12,
      name: "Lany",
      age: 25,
      location: "Marikina",
      birthday: "December 03",
      zodiac: "Sagittarius",
      hobby: "Travel",
      likes: "3.2k",
      image: HOST_PROFLE.lany.src,
      badge: "12"
    },
    {
      id: 13,
      name: "Maki",
      age: 26,
      location: "Antipolo",
      birthday: "February 28",
      zodiac: "Pisces",
      hobby: "Reading",
      likes: "2.8k",
      image: HOST_PROFLE.maki.src,
      badge: "13"
    },
    {
      id: 14,
      name: "Menggay",
      age: 24,
      location: "Caloocan",
      birthday: "September 09",
      zodiac: "Virgo",
      hobby: "Dancing",
      likes: "3.7k",
      image: HOST_PROFLE.menggay.src,
      badge: "14"
    },
    {
      id: 15,
      name: "Mica",
      age: 22,
      location: "Las Piñas",
      birthday: "March 21",
      zodiac: "Aries",
      hobby: "Beauty",
      likes: "4.1k",
      image: HOST_PROFLE.mica.src,
      badge: "15"
    },
    {
      id: 16,
      name: "Sabbie",
      age: 25,
      location: "Paranaque",
      birthday: "July 11",
      zodiac: "Cancer",
      hobby: "Movies",
      likes: "2.6k",
      image: HOST_PROFLE.sabbie.src,
      badge: "16"
    },
    {
      id: 17,
      name: "Tommy",
      age: 27,
      location: "Muntinlupa",
      birthday: "April 02",
      zodiac: "Aries",
      hobby: "Cars",
      likes: "3.9k",
      image: HOST_PROFLE.tommy.src,
      badge: "17"
    },
    {
      id: 18,
      name: "Yuri",
      age: 23,
      location: "Malabon",
      birthday: "November 19",
      zodiac: "Scorpio",
      hobby: "Anime",
      likes: "2.1k",
      image: HOST_PROFLE.yuri.src,
      badge: "18"
    }
  ];