name: aggregator
services:
  aggregator_frontend:
    build:
      context: ../
      dockerfile: docker/LocalDockerfile
    depends_on:
      aggregator_backend:
        condition: service_healthy
    ports:
      - 3000:3000
    networks:
      - aggregator_network
    volumes:
      - ../:/app
      - /app/node_modules
